version: '3'

services:
  data_stream:
    build: data_stream/
    depends_on:
      - my_mongodb 

  my_mongodb:
    image: mongo
    ports: 
      - 27017:27017

  etl:
    build: etl_job/
    depends_on: 
      - my_postgres
      - my_mongodb

  my_postgres:
    image: postgres
    ports:
     - 5551:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9876

  my_metabase:
    restart: "always"
    image: metabase/metabase
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=postgres
      - MB_DB_PORT=5432
      - MB_DB_USER=postgres
      - MB_DB_PASS=9876
      - MB_DB_HOST=my_postgres

    ports:
      - 3000:3000
